query {
  models: modelsCollection {
    total
    items {
      sys {
        id
      }
      title
      subtitle
      thumbnail {
        url
      }
      imagesCollection {
        items {
          url
        }
      }
      description {
        json
      }
      price
    }
  }
}
