query {
  modelsCollection {
    total
    items {
      title
      subtitle
      thumbnail{
        url
      }
      imagesCollection{
        items{
          url
        }
      }
      description{
        json
      }
      price
    }
  }
}