query Products {
  products {
    _id
    model {
      _id
      image
      title
      subtitle
      description
      thumbnail
      price
      categories
      size
      color
      tag
      created_at
      updated_at
    }
    size
    color
    status
    created_at
    updated_at
  }
}
